### PR TITLE
Firefox port

### PR DESCRIPTION
**Pull request by thomaspaulin**

### CODE REVIEW

**Comment by matthewAURA** [comment]
I will test this today and report back how it goes, if it is all good then we can merge @SarenCurrie

**Comment by SarenCurrie** [comment]
@matthewAURA How did your testing go?

**Comment by matthewAURA** [comment]
It didn't

**Comment by SarenCurrie** [comment]
I'll do some tomorrow. Pretty sure we're about to see the end of Cecil anyway.

**Comment by SarenCurrie** [comment]
Looks like it still works. I'll merge it and integrate it into my stupid-build (patent pending) process tomorrow. Good work @thomaspaulin

**Comment by SarenCurrie** [comment]
Thanks. Sorry about the delay.

**Pull request merged**
